name: Python LinkedList Test

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:

    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Run test case
      run: |
        python solution.py < tests/input1.txt > output.txt
        diff output.txt tests/output1.txt
